javascript-loops-practice - Alice Lee
alicejeeunlee/c0622-code-solutions pull request #38
Opened 2022-07-08 21:46 UTC by alicejeeunlee

![javascript-loops-practice](https://user-images.githubusercontent.com/106103291/178074531-f286a7fd-93b7-4b7a-a67a-d8a16dbcea3a.png)

2022-07-08 22:29 UTC, codingcodymiller requested changes

2022-07-08 22:29 UTC, codingcodymiller commented on javascript-loops-practice/filter-out-strings.js
> +    if (Number.isInteger(values[i]) === true) {
This function is meant to filter out strings, not gather all numbers. What if the input included other data types?

2022-07-08 22:29 UTC, codingcodymiller commented on javascript-loops-practice/find-index.js
> +    var index = -1;
What is the purpose of this line?

2022-07-08 23:48 UTC, alicejeeunlee commented
![javascript-loops-practice](https://user-images.githubusercontent.com/106103291/178082786-638a6537-928b-4986-9bdf-a5beb7757ef3.png)

2022-07-11 17:38 UTC, codingcodymiller approved these changes

2022-07-11 17:43 UTC, merged