express-post-json - Alice Lee
alicejeeunlee/c0622-code-solutions pull request #92
Opened 2022-08-19 23:50 UTC by alicejeeunlee

<img width="715" alt="express-post-json" src="https://user-images.githubusercontent.com/106103291/185720495-5f7274f2-1d53-4eee-8990-e001ba519f5e.png">

2022-08-19 23:51 UTC, thebearingedge requested changes

2022-08-19 23:51 UTC, thebearingedge commented on express-post-json/index.js
> +let grades = {};
Try storing your grades as properties of the object data model instead of the array.

2022-08-19 23:51 UTC, thebearingedge commented on express-post-json/index.js
> +  grades = req.body;
Instead of replacing the `grades` object, add this new one as a property, like the data model from `express-get-json`

2022-08-19 23:58 UTC, alicejeeunlee commented
<img width="824" alt="Screen Shot 2022-08-19 at 4 57 16 PM" src="https://user-images.githubusercontent.com/106103291/185720906-08d11c84-1970-4f5a-a3e8-e17669d17264.png">

2022-08-19 23:59 UTC, thebearingedge requested changes

2022-08-19 23:59 UTC, thebearingedge commented on express-post-json/index.js
> +  grades.nextId = req.body;
This will overwrite the last saved grade every time. Try this.

```js
req.body.id = nextId;
grades[nextId] = req.body;
nextId++;
```

2022-08-20 00:47 UTC, alicejeeunlee commented
<img width="906" alt="Screen Shot 2022-08-19 at 5 45 44 PM" src="https://user-images.githubusercontent.com/106103291/185722881-aa12a35b-9d99-4a0b-ba5f-13448ac08977.png">

2022-08-20 15:50 UTC, thebearingedge approved these changes

2022-08-22 16:00 UTC, merged